CREATE TABLE "nazanfeyzioglu_exhibition" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nazanfeyzioglu_exhibition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category" varchar(32) NOT NULL,
	"name" varchar(256) NOT NULL,
	"location" varchar(256) NOT NULL,
	"date" varchar(128) NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "nazanfeyzioglu_print" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nazanfeyzioglu_print_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"seriesId" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"image" text NOT NULL,
	"imageWidth" integer DEFAULT 1000 NOT NULL,
	"imageHeight" integer DEFAULT 1000 NOT NULL,
	"spec" text NOT NULL,
	"edition" text NOT NULL,
	"price" varchar(128),
	"position" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "nazanfeyzioglu_series" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nazanfeyzioglu_series_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(128) NOT NULL,
	"title" varchar(256) NOT NULL,
	"coverImage" text NOT NULL,
	"coverWidth" integer DEFAULT 1000 NOT NULL,
	"coverHeight" integer DEFAULT 1000 NOT NULL,
	"statusNote" varchar(256),
	"position" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "nazanfeyzioglu_series_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "nazanfeyzioglu_site_content" (
	"key" varchar(128) PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "nazanfeyzioglu_work" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nazanfeyzioglu_work_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"seriesId" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"image" text NOT NULL,
	"imageWidth" integer DEFAULT 1000 NOT NULL,
	"imageHeight" integer DEFAULT 1000 NOT NULL,
	"medium" text NOT NULL,
	"price" varchar(128),
	"digital" boolean DEFAULT false NOT NULL,
	"note" text,
	"position" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_print" ADD CONSTRAINT "nazanfeyzioglu_print_seriesId_nazanfeyzioglu_series_id_fk" FOREIGN KEY ("seriesId") REFERENCES "public"."nazanfeyzioglu_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_work" ADD CONSTRAINT "nazanfeyzioglu_work_seriesId_nazanfeyzioglu_series_id_fk" FOREIGN KEY ("seriesId") REFERENCES "public"."nazanfeyzioglu_series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "print_series_idx" ON "nazanfeyzioglu_print" USING btree ("seriesId");--> statement-breakpoint
CREATE INDEX "work_series_idx" ON "nazanfeyzioglu_work" USING btree ("seriesId");