CREATE TABLE "nazanfeyzioglu_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nazanfeyzioglu_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stripeCheckoutSessionId" varchar(256) NOT NULL,
	"stripePaymentIntentId" varchar(256),
	"itemType" varchar(16) NOT NULL,
	"printId" integer,
	"workId" integer,
	"itemTitle" varchar(256) NOT NULL,
	"quantity" integer NOT NULL,
	"unitAmount" integer NOT NULL,
	"amountTotal" integer NOT NULL,
	"currency" varchar(3) NOT NULL,
	"customerEmail" varchar(256),
	"customerName" varchar(256),
	"shippingAddress" jsonb,
	"paymentStatus" varchar(16) DEFAULT 'paid' NOT NULL,
	"fulfillmentStatus" varchar(16) DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "nazanfeyzioglu_order_stripeCheckoutSessionId_unique" UNIQUE("stripeCheckoutSessionId")
);
--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_print" ADD COLUMN "priceCents" integer;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_print" ADD COLUMN "editionSize" integer;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_work" ADD COLUMN "digitalPriceCents" integer;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ADD CONSTRAINT "nazanfeyzioglu_order_printId_nazanfeyzioglu_print_id_fk" FOREIGN KEY ("printId") REFERENCES "public"."nazanfeyzioglu_print"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ADD CONSTRAINT "nazanfeyzioglu_order_workId_nazanfeyzioglu_work_id_fk" FOREIGN KEY ("workId") REFERENCES "public"."nazanfeyzioglu_work"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "order_print_idx" ON "nazanfeyzioglu_order" USING btree ("printId");--> statement-breakpoint
CREATE INDEX "order_work_idx" ON "nazanfeyzioglu_order" USING btree ("workId");--> statement-breakpoint
CREATE INDEX "order_payment_intent_idx" ON "nazanfeyzioglu_order" USING btree ("stripePaymentIntentId");--> statement-breakpoint
CREATE INDEX "order_created_idx" ON "nazanfeyzioglu_order" USING btree ("createdAt");