CREATE TABLE "nazanfeyzioglu_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nazanfeyzioglu_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" integer NOT NULL,
	"itemType" varchar(16) NOT NULL,
	"printId" integer,
	"workId" integer,
	"itemTitle" varchar(256) NOT NULL,
	"quantity" integer NOT NULL,
	"unitAmount" integer NOT NULL,
	"amountTotal" integer NOT NULL,
	CONSTRAINT "order_item_quantity_positive" CHECK (quantity > 0),
	CONSTRAINT "order_item_unit_amount_nonnegative" CHECK ("unitAmount" >= 0),
	CONSTRAINT "order_item_amount_total_nonnegative" CHECK ("amountTotal" >= 0),
	CONSTRAINT "order_item_type_valid" CHECK ("itemType" in ('print', 'digital', 'original')),
	CONSTRAINT "order_item_single_item" CHECK (not ("printId" is not null and "workId" is not null))
);--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order_item" ADD CONSTRAINT "nazanfeyzioglu_order_item_orderId_nazanfeyzioglu_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."nazanfeyzioglu_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order_item" ADD CONSTRAINT "nazanfeyzioglu_order_item_printId_nazanfeyzioglu_print_id_fk" FOREIGN KEY ("printId") REFERENCES "public"."nazanfeyzioglu_print"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order_item" ADD CONSTRAINT "nazanfeyzioglu_order_item_workId_nazanfeyzioglu_work_id_fk" FOREIGN KEY ("workId") REFERENCES "public"."nazanfeyzioglu_work"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "order_item_order_idx" ON "nazanfeyzioglu_order_item" USING btree ("orderId");--> statement-breakpoint
CREATE INDEX "order_item_print_idx" ON "nazanfeyzioglu_order_item" USING btree ("printId");--> statement-breakpoint
CREATE INDEX "order_item_work_idx" ON "nazanfeyzioglu_order_item" USING btree ("workId");--> statement-breakpoint
-- Move every existing single-item order into its own order_item row before the
-- legacy line columns are dropped. Legacy orders never had tax, so the line
-- total is quantity x unit price and anything above that was shipping.
INSERT INTO "nazanfeyzioglu_order_item" ("orderId", "itemType", "printId", "workId", "itemTitle", "quantity", "unitAmount", "amountTotal")
SELECT "id", "itemType", "printId", "workId", "itemTitle", "quantity", "unitAmount", "quantity" * "unitAmount"
FROM "nazanfeyzioglu_order";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ADD COLUMN "amountSubtotal" integer;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ADD COLUMN "amountShipping" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "nazanfeyzioglu_order"
SET "amountSubtotal" = "quantity" * "unitAmount",
    "amountShipping" = GREATEST("amountTotal" - "quantity" * "unitAmount", 0);--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ALTER COLUMN "amountSubtotal" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ADD CONSTRAINT "order_amount_subtotal_nonnegative" CHECK ("amountSubtotal" >= 0);--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" ADD CONSTRAINT "order_amount_shipping_nonnegative" CHECK ("amountShipping" >= 0);--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP CONSTRAINT "order_quantity_positive";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP CONSTRAINT "order_unit_amount_nonnegative";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP CONSTRAINT "order_item_type_valid";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP CONSTRAINT "order_single_item";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP CONSTRAINT "nazanfeyzioglu_order_printId_nazanfeyzioglu_print_id_fk";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP CONSTRAINT "nazanfeyzioglu_order_workId_nazanfeyzioglu_work_id_fk";--> statement-breakpoint
DROP INDEX "order_print_idx";--> statement-breakpoint
DROP INDEX "order_work_idx";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP COLUMN "itemType";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP COLUMN "printId";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP COLUMN "workId";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP COLUMN "itemTitle";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP COLUMN "quantity";--> statement-breakpoint
ALTER TABLE "nazanfeyzioglu_order" DROP COLUMN "unitAmount";